### ISSUE TITLE
Permission denied when running as non root user with Docker

### ISSUE THREAD

**Issue by GitHK** [static-web-server/static-web-server#42]
**Warning:** I am not a Rust user and do not understand why the below is happening, nor am I amble to debug the ccode

While trying to use the below `Dockerfile` to run the static-web-server as a **non root** user.

```Dockerfile
FROM joseluisq/static-web-server:1.15.0-alpine as base

# simcore-user uid=8004(scu) gid=8004(scu) groups=8004(scu)
ENV SC_USER_ID=8004 \
    SC_USER_NAME=scu

RUN adduser -D -u ${SC_USER_ID} -s /bin/sh -h /home/${SC_USER_NAME} ${SC_USER_NAME}

# changing ownership of static-web-server files
RUN chown -R ${SC_USER_NAME}:${SC_USER_NAME} /entrypoint.sh
RUN chown -R ${SC_USER_NAME}:${SC_USER_NAME} /usr/local/bin/static-web-server
RUN chown -R ${SC_USER_NAME}:${SC_USER_NAME} /public
RUN chmod +x /usr/local/bin/static-web-server

USER ${SC_USER_NAME}
```

I get the following error

```shell
thread 'main' panicked at 'Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/server.rs:72:25
stack backtrace:
   0:     0x7fae3dfd594c - <unknown>
   1:     0x7fae3df5738c - <unknown>
   2:     0x7fae3dfd4e01 - <unknown>
   3:     0x7fae3dfd47c0 - <unknown>
   4:     0x7fae3dfd3fe9 - <unknown>
   5:     0x7fae3dff200d - <unknown>
   6:     0x7fae3dff1f7c - <unknown>
   7:     0x7fae3dff1f2d - <unknown>
   8:     0x7fae3dff1e70 - <unknown>
   9:     0x7fae3dfaaa32 - <unknown>
  10:     0x7fae3df027a7 - <unknown>
  11:     0x7fae3df01233 - <unknown>
  12:     0x7fae3df02ca2 - <unknown>
make: *** [Makefile:18: run] Error 139
```

Looks like `src/server.rs:72:25` is pointing to a piece of code just loading the files
https://github.com/joseluisq/static-web-server/blob/5cede7e92ab17ad51e93db7ad2b00edd88bf0cbd/src/server.rs#L69-L75

If you open a shell into the container you can see the files inside the `/public` exist and belong to the correct user

```shell
$ ls -lah /public/
total 32K
drwxr-xr-x    1 scu      scu         4.0K Apr 20 07:04 .
drwxr-xr-x    1 root     root        4.0K May 27 07:46 ..
-rw-r--r--    1 scu      scu          152 Apr 20 06:56 404.html
-rw-r--r--    1 scu      scu          175 Apr 20 06:56 50x.html
drwxr-xr-x    1 scu      scu         4.0K Apr 20 06:56 assets
-rw-r--r--    1 scu      scu          483 Apr 20 06:56 index.html
```

### How to test

```bash
git clone https://github.com/GitHK/issue-static-web-server.git
cd issue-static-web-server
make build
make run
```

**Repo  to reproduce the issue:** https://github.com/GitHK/issue-static-web-server

**Comment by joseluisq** [comment]
> **Warning:** I am not a Rust user and do not understand why the below is happening, nor am I amble to debug the ccode
>
> While trying to use the below `Dockerfile` to run the static-web-server as a **non root** user.
> 
> ```dockerfile
> FROM joseluisq/static-web-server:1.15.0-alpine as base
> 
> # simcore-user uid=8004(scu) gid=8004(scu) groups=8004(scu)
> ENV SC_USER_ID=8004 \
>     SC_USER_NAME=scu
> 
> RUN adduser -D -u ${SC_USER_ID} -s /bin/sh -h /home/${SC_USER_NAME} ${SC_USER_NAME}
> 
> # changing ownership of static-web-server files
> RUN chown -R ${SC_USER_NAME}:${SC_USER_NAME} /entrypoint.sh
> RUN chown -Rdocker run --rm -it custom-static-webserver:latest id uid=8004(scu) gid=8004(scu) ${SC_USER_NAME}:${SC_USER_NAME} /usr/local/bin/static-web-server
> RUN chown -R ${SC_USER_NAME}:${SC_USER_NAME} /public
> RUN chmod +x /usr/local/bin/static-web-server
> 
> USER ${SC_USER_NAME}
> ```

I did the same using your repo and I didn't get the error.
The container is using the provided user.
```sh
$ docker run --rm -it custom-static-webserver:latest id
uid=8004(scu) gid=8004(scu)
```

The container is just running

```sh
$ docker run --rm -it -p 8787:80 custom-static-webserver:latest
2021-05-27T13:01:27 [SERVER] - HTTP Server is listening on [::]:80
```

and the /public dir has the user permissions.

```sh
$ docker run --rm -it custom-static-webserver:latest ls -lah /public
total 28K    
drwxr-xr-x    1 scu      scu         4.0K Apr 20 07:04 .
drwxr-xr-x    1 root     root        4.0K May 27 13:13 ..
-rw-r--r--    1 scu      scu          152 Apr 20 06:56 404.html
-rw-r--r--    1 scu      scu          175 Apr 20 06:56 50x.html
drwxr-xr-x    1 scu      scu         4.0K Apr 20 06:56 assets
-rw-r--r--    1 scu      scu          483 Apr 20 06:56 index.html
```

I would be useful if you can provide more info about your environment, your docker setup, os, or other relevant info to try to figure it out.

**Comment by joseluisq** [comment]
> Looks like `src/server.rs:72:25` is pointing to a piece of code just loading the files
> https://github.com/joseluisq/static-web-server/blob/5cede7e92ab17ad51e93db7ad2b00edd88bf0cbd/src/server.rs#L69-L75

No, this is `master` branch which belongs to v2 actually in beta. You are using v1 at `1.x` branch.

**Comment by joseluisq** [comment]
Since the v1 executable is a release binary, It has no debug tracing so I could provide you a development binary with debug  enabled if you want so you could get more details about the error in order to find why it occurs.

However for me the error looks like something with the permissions were not given properly.

**Comment by GitHK** [comment]
I've just now seen all the posts.

I've also tried on a different machine (macOS) and it works. It starts without any issues.

The error comes form my development box which is has the below configuration.

```
------------------------------ environs -----------------------------------
SHELL=/usr/bin/zsh
LSCOLORS=Gxfxcxdxbxegedabagacad
PYENV_SHELL=zsh
LESS=-R
PYENV_ACTIVATE_SHELL=1
LC_ADDRESS=de_CH.UTF-8
LC_NAME=de_CH.UTF-8
P9K_TTY=old
LC_MONETARY=de_CH.UTF-8
PYENV_VERSION=osparc-simcore-forked
PWD=/home/user/work/pr-osparc-sidecar
PYENV_VIRTUALENV_INIT=1
LOGNAME=user
XDG_SESSION_TYPE=tty
MOTD_SHOWN=pam
HOME=/home/user
LC_PAPER=de_CH.UTF-8
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
VIRTUAL_ENV=/home/user/.pyenv/versions/3.6.10/envs/osparc-simcore-forked
LC_TERMINAL=iTerm2
SSH_CONNECTION=172.16.9.34 58386 10.43.103.168 22
XDG_SESSION_CLASS=user
LC_IDENTIFICATION=de_CH.UTF-8
TERM=xterm-256color
ZSH=/home/user/.oh-my-zsh
USER=user
LC_TERMINAL_VERSION=3.4.8
PYENV_VIRTUAL_ENV=/home/user/.pyenv/versions/3.6.10/envs/osparc-simcore-forked
SHLVL=2
PAGER=less
LC_TELEPHONE=de_CH.UTF-8
LC_MEASUREMENT=de_CH.UTF-8
XDG_SESSION_ID=1603
LC_CTYPE=UTF-8
XDG_RUNTIME_DIR=/run/user/1001
SSH_CLIENT=172.16.9.34 58386 22
LC_TIME=de_CH.UTF-8
P9K_SSH=1
LC_ALL=en_US.UTF-8
PATH=/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
_OLD_VIRTUAL_PS1=%b%k%s%u%F{%(?.076.196)}${${P9K_CONTENT::="❯"}+}${:-"❯"}%b%k%f%s%u
SSH_TTY=/dev/pts/5
LC_NUMERIC=de_CH.UTF-8
OLDPWD=/home/user
_=/usr/bin/env
------------------------------ uname -----------------------------------
Linux hostname 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
------------------------------ python -----------------------------------
/home/user/.pyenv/shims/python
Python 3.6.10
------------------------------ python3 -----------------------------------
/home/user/.pyenv/shims/python3
Python 3.6.10
------------------------------ docker -----------------------------------
/usr/bin/docker
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Oct 14 16:41:21 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.3.3-0ubuntu2.1
  GitCommit:
 nvidia:
  Version:          spec: 1.0.2-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
------------------------------ docker buildx-----------------------------------
/usr/bin/docker
github.com/docker/buildx v0.4.2 fb7b670b764764dc4716df3eba07ffdae4cc47b2
------------------------------ docker-compose -----------------------------------
/home/user/.pyenv/shims/docker-compose
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
/tmp
```

**Comment by joseluisq** [comment]
I think that this binary with debug info enabled could help to identify the error and throw more details.  
Please use this binary below in your dev environment along with `RUST_BACKTRACE=1` env then share the backtrace here to get more context about it.

Linux Musl x86_64 - [static-web-server-1.16.0-debug.zip](https://github.com/joseluisq/static-web-server/files/6554562/static-web-server-1.16.0-debug.zip)

**Comment by GitHK** [comment]
Result with `RUST_BACKTRACE=1`

```
thread 'main' panicked at 'Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/server.rs:72:25
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at ./rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
   2: static_web_server::server::run
   3: static_web_server::main
             at ./home/joseluisq/devel/labs/static-web-server/src/bin/server.rs:11:5
   4: core::ops::function::FnOnce::call_once
             at ./home/joseluisq/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Result with `RUST_BACKTRACE=full`
```
thread 'main' panicked at 'Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/server.rs:72:25
stack backtrace:
   0:     0x7f887384089c - std::backtrace_rs::backtrace::libunwind::trace::h88fc75946fefc1bd
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f887384089c - std::backtrace_rs::backtrace::trace_unsynchronized::h4b97f8a8dd813b09
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f887384089c - std::sys_common::backtrace::_print_fmt::h0927c9e7182c7202
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f887384089c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc1987df659564b2a
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f88737cbbaf - core::fmt::write::hc51f928bb58894fa
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x7f887383fd61 - std::io::Write::write_fmt::haa954040c2b50760
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x7f887383f730 - std::sys_common::backtrace::_print::hdfa186acd85ec26d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f887383f730 - std::sys_common::backtrace::print::h6f8092ac7e59ede0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f887383f730 - std::panicking::default_hook::{{closure}}::h6302fe8dc8dca2bd
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x7f887383ec49 - std::panicking::default_hook::h2c929b967d67157b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x7f887383ec49 - std::panicking::rust_panic_with_hook::h91673b6533edde82
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x7f887385ac8d - std::panicking::begin_panic_handler::{{closure}}::hda9284becd3f5dc5
  12:     0x7f887385abfc - std::sys_common::backtrace::__rust_end_short_backtrace::h2b5f855bab872d88
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x7f887385abad - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x7f8873779c50 - std::panicking::begin_panic_fmt::h65999802f3ffaf17
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
  15:     0x7f8873819bc0 - static_web_server::server::run::hc1fb77500e37f426
  16:     0x7f887377c59f - static_web_server::main::h503c6b7c3e8cb270
                               at /home/joseluisq/devel/labs/static-web-server/src/bin/server.rs:11:5
  17:     0x7f887377b283 - core::ops::function::FnOnce::call_once::h679e8485d8ddd2cd
                               at /home/joseluisq/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  18:     0x7f887377b283 - std::sys_common::backtrace::__rust_begin_short_backtrace::h04e0499be4090df2
                               at /home/joseluisq/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  19:     0x7f887377c9e2 - main
```

**Comment by joseluisq** [comment]
Thanks, I'm going to investigate how to reproduce it.

**Comment by GitHK** [comment]
Thanks a lot for the support. Please let me know if I can be of use.

**Comment by joseluisq** [comment]
I think I found the issue cause. Can you simply change the default port 80 to something higher than 1023?
I suspect that it could be problem since your non-root user obviously doesn't have privileges to port 80 in your environment or your environment itself doesn't allow it.

**Comment by GitHK** [comment]
Yes, changing the port worked as expected. Now that you pointed it out, it was so obvious! Thanks a lot.

**Comment by joseluisq** [comment]
Don't worry, the error message was not clear so I've improved a bit by the way.
